export const goalsClasses = {
  root: "goals",
  header: {
    head: "goals__header",
    title: "goals__title",
    subtitle: "goals__subtitle",
  },
  flow: {
    root: "goals-flow",
    atmosphere: "goals-flow__atmosphere",
    glow: "goals-flow__glow",
    grid: "goals-flow__grid",
    particles: "goals-flow__particles",
    path: "goals-flow__path",
    pathAura: "goals-flow__pathAura",
    pathLine: "goals-flow__pathLine",
    pathFlow: "goals-flow__pathFlow",
    pathNode: "goals-flow__pathNode",
    pathNodeInner: "goals-flow__pathNodeInner",
    list: {
      root: "goals__list",
      item: "goals__item",
      card: "goals__card",
      top: "goals__top",
      icon: "goals__icon",
      number: "goals__number",
      label: "goals__label",
      text: "goals__text",
    },
  },
}
