export { HeroSection } from "./HeroSection"
export { WhatIDoSection } from "./WhatIDoSection"
export { ExperienceSection } from "./ExperienceSection"
export { ProcessSection } from "./ProcessSection"
export { GoalsSection } from "./GoalsSection"
